### ISSUE TITLE
Add a link to behind the scenes blogpost somewhere

### ISSUE THREAD

**Issue by alisondavis17** [balenalabs/fold-for-covid-landing#102]
@chrisys @andrewnhem can you help find the best place to link to the [blog post](https://www.balena.io/blog/balena-enables-more-devices-to-join-rosetta-home-to-research-covid-19/) from the landing page?

**Comment by andrewnhem** [comment]
@iamsolankiamit / @sradevski One potential place to link to the blog post is in the first FAQ item. I also included some fixes since its formatting looked a bit odd. Recommendation:

## Why are we doing this?

At [balena](https://www.balena.io/), we love open source initiatives that try to make the world a better place. After learning about the [Rosetta team’s great work](https://boinc.bakerlab.org/), we felt we could help make an impact by allowing folks to easily add their spare computers and devices to the platform.

Lending our engineering expertise to streamline the process, including fantastic community support, we created the Fold for Covid project to help promote the project and try to get as many people involved as we can, so that scientists and researchers can start to identify potential treatments for COVID-19 as quickly as possible. Learn more about the project by [reading this blog post](https://www.balena.io/blog/balena-enables-more-devices-to-join-rosetta-home-to-research-covid-19/).

Try the project out, come join us on the [Forums](https://forums.balena.io/c/fold-for-covid/), submit fixes or improvements, or add features to the [Fold for Covid Github repository](https://github.com/balenalabs/rosetta-at-home).

**Comment by andrewnhem** [comment]
@iamsolankiamit / @sradevski  Another place to link to the post without bloating the first main paragraph below the map is as such:

## What is Fold for Covid, and how does it help?
The Fold for Covid project aims to make it easy to donate spare compute capacity to support COVID-19 research with a few simple steps. [This effort](https://www.balena.io/blog/balena-enables-more-devices-to-join-rosetta-home-to-research-covid-19/) contributes to the [Rosetta@Home project](https://boinc.bakerlab.org/), led by the [Baker Laboratory at the University of Washington](https://www.bakerlab.org/), which uses distributed computing to help scientists and doctors find potential treatments for COVID-19.
